Portfolio_Website/Portfolio_Website/Controllers/EducationController.cs
using BusinnesLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Portfolio_Website.Controllers
{
    [Authorize]
    public class EducationController : Controller
    {
        SchoolManager manager = new SchoolManager(new EfSchoolDal());
        public IActionResult EducationIndex()
        {
            var values = manager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult EducationAdd()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EducationAdd(School p)
        {
            manager.TAdd(p);
            return RedirectToAction("EducationIndex");
        }

        public IActionResult EducationDelete(int id)
        {
            var values = manager.TGetByID(id);
            manager.TDelete(values);
            return RedirectToAction("EducationIndex");
        }
        [HttpGet]
        public IActionResult EducationUpdate(int id)
        {
            var values = manager.TGetByID(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult EducationUpdate(School school)
        {
            manager.TUpdate(school);
            return RedirectToAction("EducationIndex");
        }
    }
}

Portfolio_Website/Portfolio_Website/Views/Education/EducationAdd.cshtml
@model EntityLayer.Concrete.School
@{
    ViewData["Title"] = "EducationAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 style="color:white;font-weight:bold;text-align:center;margin-top:20px;">Education Add Alanı</h2>
<br />
<br />
@using (Html.BeginForm("EducationAdd", "Education", FormMethod.Post))
{
    <div>
        @Html.LabelFor(x => x.SchoolID)
        @Html.TextBoxFor(x => x.SchoolID, new { @class = "form-control", @readonly = "readonly" })

    </div>



    <div>
        <label>NAME</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control", })

    </div>

    <div>
        <label>DATE</label>
        @Html.TextBoxFor(x => x.Date, new { @class = "form-control", })

    </div>

  
    
    <div>
        <label>SECTİON</label>
        @Html.TextBoxFor(x => x.Section, new { @class = "form-control", })

    </div>

    <div>
        <label>ımage</label>
        @Html.TextBoxFor(x => x.Image, new { @class = "form-control", })

    </div>
    <br />
    <button class="btn btn-primary">EKLE</button>
}

Portfolio_Website/Portfolio_Website/Views/Education/EducationIndex.cshtml
@using EntityLayer.Concrete
@model List<School>
@{
    ViewData["Title"] = "EducationIndex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 style="color:white;font-weight:bold;text-align:center;margin-top:20px;">Education Alanı</h2>
<br />



<table class="table table-bordered">

    <tr style="width:50px;">
        <th>ID</th>
        <th>NAME</th>
        <th>DATE</th>
       
        <th>SECTİON</th>
        <th>GÜNCELLE</th>
        <th>SİL</th>

    </tr>

    <tbody style="width:50px;">
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.SchoolID</td>
                <td>@x.Name</td>
                <td>@x.Date</td>
               
                <td>@x.Section</td>
                <td>
                    <a href="/Education/EducationUpdate/@x.SchoolID" class="btn btn-success">GÜNCELLE</a>
                </td>
                <td>
                    <a href="/Education/EducationDelete/@x.SchoolID" class="btn btn-danger">SİL</a>
                </td>


            </tr>
        }



    </tbody>
</table>

<a href="/Education/EducationAdd"><button class="btn btn-primary"> YENİ EĞİTİM EKLE</button></a>

Portfolio_Website/Portfolio_Website/Views/Education/EducationUpdate.cshtml
@model EntityLayer.Concrete.School
@{
    ViewData["Title"] = "EducationUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 style="color:white;font-weight:bold;text-align:center;margin-top:20px;">Education Update Alanı</h2>
<br />
<br />
@using (Html.BeginForm("EducationUpdate", "Education", FormMethod.Post))
{
    <div>
        @Html.LabelFor(x => x.SchoolID)
        @Html.TextBoxFor(x => x.SchoolID, new { @class = "form-control", @readonly = "readonly" })

    </div>



    <div>
        <label>NAME</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control", })

    </div>

    <div>
        <label>DATE</label>
        @Html.TextBoxFor(x => x.Date, new { @class = "form-control", })

    </div>

  


    <div>
        <label>SECTİON</label>
        @Html.TextBoxFor(x => x.Section, new { @class = "form-control", })

    </div>

    <div>
        <label>IMAGE</label>
        @Html.TextBoxFor(x => x.Image, new { @class = "form-control", })

    </div>
    <br />
    <button class="btn btn-primary">Güncelle</button>
}