Portfolio_Website/Portfolio_Website/Controllers/SkillController.cs
using BusinnesLayer.Concrete;
using BusinnesLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Portfolio_Website.Controllers
{
    [Authorize]
    public class SkillController : Controller
    {
        SkillManager manager = new SkillManager(new EfSkillDal());
        public IActionResult SkillIndex()
        {
            var values = manager.TGetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult SkillAdd()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SkillAdd(Skill p)
        {
            SkillValidator validations= new SkillValidator();

            ValidationResult result=validations.Validate(p);
            if (result.IsValid)
            {
                manager.TAdd(p);
                return RedirectToAction("SkillIndex");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
           
        }

        public IActionResult SkillDelete(int id)
        {
            var values = manager.TGetByID(id);
            manager.TDelete(values);
            return RedirectToAction("SkillIndex");
        }

        [HttpGet]
        public IActionResult SkillUpdate(int id)
        {
            var values = manager.TGetByID(id);
            return View(values);

        }

        [HttpPost]
        public IActionResult SkillUpdate(Skill skill)
        {
            manager.TUpdate(skill);
            return RedirectToAction("SkillIndex");

        }
    }
}

Portfolio_Website/Portfolio_Website/Views/Skill/SkillAdd.cshtml
@model EntityLayer.Concrete.Skill
@{
    ViewData["Title"] = "SkillAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 style="color:white;font-weight:bold;text-align:center;margin-top:20px;">Skill Add Alanı</h2>
<br />
<br />
@using (Html.BeginForm("SkillAdd", "Skill", FormMethod.Post))
{
    <div>
        @Html.LabelFor(x => x.SkillId)
        @Html.TextBoxFor(x => x.SkillId, new { @class = "form-control", @readonly = "readonly" })

    </div>



    <div>
        <label>TITLE</label>
        @Html.TextBoxFor(x => x.Title, new { @class = "form-control", })

    </div>

    <div>
        <label>VALUE</label>
        @Html.TextBoxFor(x => x.Value, new { @class = "form-control", })
        @Html.ValidationMessageFor(x => x.Value)

    </div>

    <br />
    <button class="btn btn-primary">EKLE</button>
}

Portfolio_Website/Portfolio_Website/Views/Skill/SkillIndex.cshtml
@using EntityLayer.Concrete
@model List<Skill>
@{
    ViewData["Title"] = "SkillIndex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 style="color:white;font-weight:bold;text-align:center;margin-top:20px;">Skilss Alanı</h2>
<br />



<table class="table table-bordered">

    <tr>
        <th>ID</th>
        <th>TİTLE</th>
        <th>VALUE</th>
        <th>GÜNCELLE</th>
        <th>SİL</th>
       
    </tr>

    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.SkillId</td>
                <td>@x.Title</td>
                <td>
                    <div class="progress-bar" role="progressbar" style="width: @x.Value%;" aria-valuenow="@x.Value" aria-valuemin="0" aria-valuemax="100">
                        @x.Value%
                    </div>
                </td>
                <td>
                    <a href="/Skill/SkillUpdate/@x.SkillId" class="btn btn-success">GÜNCELLE</a>
                </td>
                <td>
                    <a href="/Skill/SkillDelete/@x.SkillId" class="btn btn-danger">SİL</a>
                </td>
                


            </tr>
        }



    </tbody>
</table>

<a href="/Skill/SkillAdd">

    <button class="btn btn-primary"> YENİ YETENEK EKLE</button>

</a>

Portfolio_Website/Portfolio_Website/Views/Skill/SkillUpdate.cshtml
@model EntityLayer.Concrete.Skill
@{
    ViewData["Title"] = "SkillUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 style="color:white;font-weight:bold;text-align:center;margin-top:20px;">Skill Update Alanı</h2>
<br />
<br />
@using (Html.BeginForm("SkillUpdate", "Skill", FormMethod.Post))
{
    <div>
        @Html.LabelFor(x => x.SkillId)
        @Html.TextBoxFor(x => x.SkillId, new { @class = "form-control", @readonly = "readonly" })

    </div>



    <div>
        <label>TITLE</label>
        @Html.TextBoxFor(x => x.Title, new { @class = "form-control", })

    </div>

    <div>
        <label>VALUE</label>
        @Html.TextBoxFor(x => x.Value, new { @class = "form-control", })

    </div>

    <br />
    <button class="btn btn-primary">GÜNCELLE</button>
}